# Generated by Django 3.2 on 2023-04-14 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_achievement_achievmentcat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AchievmentCat',
            new_name='AchievementCat',
        ),
        migrations.RenameField(
            model_name='achievementcat',
            old_name='achievment',
            new_name='achievement',
        ),
    ]
